---
abstract: 'Deal with Library-of-Congress call numbers'
author:
  - 'Daniel Wells <dbw2@calvin.edu>'
build_requires:
  Math::BigInt: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Library-CallNumber-LC
provides:
  Library::CallNumber::LC:
    file: lib/Library/CallNumber/LC.pm
    version: 0.20
requires:
  Math::BigInt: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.20
